using System.ComponentModel.DataAnnotations.Schema;

namespace MigrateDatabase.MssqlEntities.Arcadia;

public class MSSQLItemResource
{
    public int id { get; set; }
    public int name_id { get; set; }
    public int tooltip_id { get; set; }
    public int type { get; set; }
    public int group { get; set; }
    [Column("class")]
    public int Class { get; set; }
    public int wear_type { get; set; }
    [Column("set_id")]
    public int SetId { get; set; }
    public int set_part_flag { get; set; }
    public byte grade { get; set; }
    public int rank { get; set; }
    public int level { get; set; }
    public int enhance { get; set; }
    public int socket { get; set; }
    public int status_flag { get; set; }
    public string limit_deva { get; set; }
    public string limit_asura { get; set; }
    public string limit_gaia { get; set; }
    public byte job_depth { get; set; }
    public string limit_fighter { get; set; }
    public string limit_hunter { get; set; }
    public string limit_magician { get; set; }
    public string limit_summoner { get; set; }
    public int use_min_level { get; set; }
    public int use_max_level { get; set; }
    public int target_min_level { get; set; }
    public int target_max_level { get; set; }
    public decimal range { get; set; }
    public decimal weight { get; set; }
    public int price { get; set; }
    public int huntaholic_point { get; set; }
    public int ethereal_durability { get; set; }
    public int endurance { get; set; }
    public int material { get; set; }
    public int summon_id { get; set; }
    public int item_use_flag { get; set; }
    public int available_period { get; set; }
    public byte decrease_type { get; set; }
    public decimal throw_range { get; set; }
    public short base_type_0 { get; set; }
    public decimal base_var1_0 { get; set; }
    public decimal base_var2_0 { get; set; }
    public short base_type_1 { get; set; }
    public decimal base_var1_1 { get; set; }
    public decimal base_var2_1 { get; set; }
    public short base_type_2 { get; set; }
    public decimal base_var1_2 { get; set; }
    public decimal base_var2_2 { get; set; }
    public short base_type_3 { get; set; }
    public decimal base_var1_3 { get; set; }
    public decimal base_var2_3 { get; set; }
    public short opt_type_0 { get; set; }
    public decimal opt_var1_0 { get; set; }
    public decimal opt_var2_0 { get; set; }
    public short opt_type_1 { get; set; }
    public decimal opt_var1_1 { get; set; }
    public decimal opt_var2_1 { get; set; }
    public short opt_type_2 { get; set; }
    public decimal opt_var1_2 { get; set; }
    public decimal opt_var2_2 { get; set; }
    public short opt_type_3 { get; set; }
    public decimal opt_var1_3 { get; set; }
    public decimal opt_var2_3 { get; set; }
    public int effect_id { get; set; }
    public short enhance_0_id { get; set; }
    public decimal enhance_0_01 { get; set; }
    public decimal enhance_0_02 { get; set; }
    public decimal enhance_0_03 { get; set; }
    public decimal enhance_0_04 { get; set; }
    public short enhance_1_id { get; set; }
    public decimal enhance_1_01 { get; set; }
    public decimal enhance_1_02 { get; set; }
    public decimal enhance_1_03 { get; set; }
    public decimal enhance_1_04 { get; set; }
    public int skill_id { get; set; }
    public int state_id { get; set; }
    public int state_level { get; set; }
    public int state_time { get; set; }
    public int cool_time { get; set; }
    public short cool_time_group { get; set; }
    public int model_type_dem { get; set; }
    public int model_type_def { get; set; }
    public int model_type_asm { get; set; }
    public int model_type_asf { get; set; }
    public int model_type_gam { get; set; }
    public int model_type_gaf { get; set; }
    public byte deco_model_change { get; set; }
    public string model_00 { get; set; }
    public string model_01 { get; set; }
    public string model_02 { get; set; }
    public string model_03 { get; set; }
    public string model_04 { get; set; }
    public string model_05 { get; set; }
    public string model_06 { get; set; }
    public string model_07 { get; set; }
    public string model_08 { get; set; }
    public string model_09 { get; set; }
    public string model_10 { get; set; }
    public string model_11 { get; set; }
    public string model_12 { get; set; }
    public string model_13 { get; set; }
    public string model_14 { get; set; }
    public string model_15 { get; set; }
    public string model_16 { get; set; }
    public string model_17 { get; set; }
    public string texture_filename { get; set; }
    public string drop_type { get; set; }
    public int icon_id { get; set; }
    public string icon_file_name { get; set; }
    public string script_text { get; set; }
}